// this file is generated by bin/getContextMaps.sh
export default [ { name: 'indigenous_areas', layergroupid: 'p2cs-sei@13f42896@b5aa14466aa398a4f6f3a820d083bc4e:1448500494201' }, { name: 'brazil_protected', layergroupid: 'p2cs-sei@09259164@75aea9aabaca69aacd267cfbf76aa428:1476798795723' }, { name: 'silos', layergroupid: 'p2cs-sei@c3ab06cb@9c20e01d34445cd0e3d124eb13185b18:1476875895402' } ]
