// this file is generated by bin/getContextMaps.sh
export default [ { name: 'indigenous_areas', layergroupid: 'p2cs-sei@b51d2edc@c176a73539feb243315ad0c0e6f30672:1448500494201' }, { name: 'brazil_protected', layergroupid: 'p2cs-sei@d46887f0@addb210df76ab28f888d77027557a944:1476798795723' }, { name: 'silos', layergroupid: 'p2cs-sei@7cf99f54@ee056b0cea256ea0304ce9728ce7a6f2:1476875895402' } ]
