rules:
  property-sort-order:
    - 0
    - order: 'smacss'
  force-element-nesting:
    - 0
  no-color-literals:
    - 1
    -
      allow-rgba: true
  no-url-protocols:
    - 0
  nesting-depth:
    - 1
    -
      max-depth: 4
  no-vendor-prefixes: 0
  single-line-per-selector:
    - 0
  force-pseudo-nesting:
    - 0
  hex-notation:
    - 0
files:
  ignore:
    - 'styles/_reset.scss'
