rules:
  property-sort-order:
    - 1
    - order: 'smacss'
  force-element-nesting:
    - 0
  no-color-literals:
    - 1
    -
      allow-rgba: true
  no-url-protocols:
    - 0
  nesting-depth:
    - 1
    -
      max-depth: 3
  no-vendor-prefixes: 0
  single-line-per-selector:
    - 0
