export default {
  LOAD_INITIAL_DATA: 'LOAD_INITIAL_DATA',
  GET_COLUMNS: 'GET_COLUMNS',
  LOAD_LINKS: 'LOAD_LINKS',
  GET_LINKS: 'GET_LINKS',
  HIGHLIGHT_NODE: 'HIGHLIGHT_NODE',
  SELECT_NODE: 'SELECT_NODE',
  RESIZE: 'RESIZE',
  SELECT_COUNTRY: 'SELECT_COUNTRY',
  SELECT_COMMODITY: 'SELECT_COMMODITY',
  SELECT_YEARS: 'SELECT_YEARS',
  SELECT_QUANT: 'SELECT_QUANT',
  SELECT_QUAL: 'SELECT_QUAL'
};
